name: Deploy Static Website to AWS S3

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    tags: '*'
    branches:
      - main

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
